[package]
name = "tangram_package"

description = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = false
repository = { workspace = true }
version = { workspace = true }

[dev-dependencies]
tangram_server = { workspace = true }

[dependencies]
async-recursion = { workspace = true }
async-trait = { workspace = true }
fnv = { workspace = true }
futures = { workspace = true }
im = { workspace = true }
itertools = { workspace = true }
semver = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tangram_client = { workspace = true }
tangram_error = { workspace = true }
tangram_language = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
