[package]
name = "tangram_util"

authors.workspace = true
description.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[lints]
workspace = true

[dependencies]
bytes = { workspace = true }
data-encoding = { workspace = true }
libc = { workspace = true }
derive_more = { workspace = true }
fnv = { workspace = true }
futures = { workspace = true }
im = { workspace = true }
num = { workspace = true }
rustix = { workspace = true }
serde = { workspace = true }
serde-untagged = { workspace = true }
serde_with = { workspace = true }
tangram_either = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
xattr = { workspace = true }
