name = "Tangram JavaScript"
grammar = "javascript"
path_suffixes = [
    "tangram.js",
    "tg.js",
]
first_line_pattern = '^#!.*\b(?:[/ ]node|deno run.*--ext[= ]js)\b'
line_comments = ["// "]
autoclose_before = ";:.,=}])>"
word_characters = [
    "$",
    "#",
]
tab_size = 2
scope_opt_in_language_servers = [
    "tailwindcss-language-server",
    "emmet-language-server",
]
prettier_parser_name = "babel"
debuggers = ["JavaScript"]
import_path_strip_regex = '(?:/index)?\.[jt]s$'

[[brackets]]
start = "{"
end = "}"
close = true
newline = true

[[brackets]]
start = "["
end = "]"
close = true
newline = true

[[brackets]]
start = "("
end = ")"
close = true
newline = true

[[brackets]]
start = "<"
end = ">"
close = false
newline = true
not_in = [
    "comment",
    "string",
]

[[brackets]]
start = '"'
end = '"'
close = true
newline = false
not_in = [
    "comment",
    "string",
]

[[brackets]]
start = "'"
end = "'"
close = true
newline = false
not_in = [
    "comment",
    "string",
]

[[brackets]]
start = "`"
end = "`"
close = true
newline = false
not_in = [
    "comment",
    "string",
]

[[brackets]]
start = "/*"
end = " */"
close = true
newline = false
not_in = [
    "comment",
    "string",
]

[block_comment]
start = "/*"
prefix = "* "
end = "*/"
tab_size = 1

[documentation_comment]
start = "/**"
prefix = "* "
end = "*/"
tab_size = 1

[wrap_characters]
start_prefix = "<"
start_suffix = ">"
end_prefix = "</"
end_suffix = ">"

[jsx_tag_auto_close]
open_tag_node_name = "jsx_opening_element"
close_tag_node_name = "jsx_closing_element"
jsx_element_node_name = "jsx_element"
tag_name_node_name = "identifier"

[overrides.default]
linked_edit_characters = ["."]

[overrides.element]
opt_into_language_servers = ["emmet-language-server"]

[overrides.element.line_comments]
remove = true

[overrides.element.block_comment]
start = "{/* "
prefix = ""
end = "*/}"
tab_size = 0

[overrides.string]
completion_query_characters = [
    "-",
    ".",
]
opt_into_language_servers = ["tailwindcss-language-server"]
