[package]
name = "tangram_database"

description = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = false
repository = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }

[lints]
workspace = true

[features]
postgres = ["dep:tokio-postgres"]

[dependencies]
bytes = { workspace = true }
derive_more = { workspace = true }
fnv = { workspace = true }
futures = { workspace = true }
indexmap = { workspace = true }
itertools = { workspace = true }
num = { workspace = true }
rusqlite = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tangram_either = { workspace = true }
tokio = { workspace = true }
tokio-postgres = { workspace = true, optional = true }
tracing = { workspace = true }
url = { workspace = true }
