[package]
name = "tangram_builtin"

description = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = false
repository = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }

[lints]
workspace = true

[dependencies]
async-channel = { workspace = true }
async-compression = { workspace = true }
astral-tokio-tar = { workspace = true }
async_zip = { workspace = true }
futures = { workspace = true }
num = { workspace = true }
reqwest = { workspace = true }
tangram_client = { workspace = true }
tangram_futures = { workspace = true }
tangram_temp = { workspace = true }
tangram_uri = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
