name = "Tangram TypeScript"
grammar = "typescript"
path_suffixes = [
    "tangram.ts",
    "tg.ts",
]
first_line_pattern = '^#!.*\b(?:deno run|ts-node|bun|tsx|[/ ]node)\b'
line_comments = ["// "]
autoclose_before = ";:.,=}])>"
word_characters = [
    "#",
    "$",
]
prettier_parser_name = "typescript"
tab_size = 2
debuggers = ["JavaScript"]
scope_opt_in_language_servers = ["tailwindcss-language-server"]
import_path_strip_regex = '(?:/index)?\.[jt]s$'

[[brackets]]
start = "{"
end = "}"
close = true
newline = true

[[brackets]]
start = "["
end = "]"
close = true
newline = true

[[brackets]]
start = "("
end = ")"
close = true
newline = true

[[brackets]]
start = "<"
end = ">"
close = false
newline = true
not_in = [
    "string",
    "comment",
]

[[brackets]]
start = '"'
end = '"'
close = true
newline = false
not_in = ["string"]

[[brackets]]
start = "'"
end = "'"
close = true
newline = false
not_in = [
    "string",
    "comment",
]

[[brackets]]
start = "`"
end = "`"
close = true
newline = false
not_in = ["string"]

[[brackets]]
start = "/*"
end = " */"
close = true
newline = false
not_in = [
    "string",
    "comment",
]

[block_comment]
start = "/*"
prefix = "* "
end = "*/"
tab_size = 1

[documentation_comment]
start = "/**"
prefix = "* "
end = "*/"
tab_size = 1

[wrap_characters]
start_prefix = "<"
start_suffix = ">"
end_prefix = "</"
end_suffix = ">"

[overrides.string]
completion_query_characters = [
    "-",
    ".",
]
opt_into_language_servers = ["tailwindcss-language-server"]
prefer_label_for_snippet = true

[overrides.function_name_before_type_arguments]
prefer_label_for_snippet = true
