[package]
name = "tangram_store"

description = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = false
repository = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }

[lints]
workspace = true

[features]
default = ["lmdb"]
foundationdb = ["dep:foundationdb", "dep:tangram_fdb"]
lmdb = ["dep:heed"]
scylla = ["dep:scylla"]

[dependencies]
aws-credential-types = { workspace = true }
aws-sigv4 = { workspace = true }
byteorder = { workspace = true }
bytes = { workspace = true }
dashmap = { workspace = true }
derive_more = { workspace = true }
foundationdb = { workspace = true, optional = true }
foundationdb-tuple = { workspace = true }
futures = { workspace = true }
heed = { workspace = true, optional = true }
http = { workspace = true }
indoc = { workspace = true }
num = { workspace = true }
reqwest = { workspace = true }
scylla = { workspace = true, optional = true }
serde = { workspace = true }
serde_json = { workspace = true }
tangram_client = { workspace = true }
tangram_fdb = { workspace = true, optional = true }
tangram_serialize = { workspace = true }
tangram_uri = { workspace = true }
time = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
