[package]
name = "tangram_store"

description = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = false
repository = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }

[lints]
workspace = true

[features]
default = ["lmdb", "scylla"]
lmdb = ["dep:heed"]
scylla = ["dep:scylla"]

[dependencies]
byteorder = { workspace = true }
bytes = { workspace = true }
dashmap = { workspace = true }
derive_more = { workspace = true }
foundationdb-tuple = { workspace = true }
futures = { workspace = true }
heed = { workspace = true, optional = true }
indoc = { workspace = true }
num = { workspace = true }
scylla = { workspace = true, optional = true }
serde = { workspace = true }
serde_json = { workspace = true }
tangram_client = { workspace = true }
tangram_serialize = { workspace = true }
time = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
