[package]
name = "tangram_vfs"

description = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = false
repository = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }

[lints]
workspace = true

[dev-dependencies]
clap = { workspace = true }
tracing-subscriber = { workspace = true }

[dependencies]
async-channel = { workspace = true }
bytes = { workspace = true }
dashmap = { workspace = true }
futures = { workspace = true }
io-uring = "0.7"
libc = { workspace = true }
num = { workspace = true }
tangram_either = { workspace = true }
tangram_futures = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
tracing = { workspace = true }
zerocopy = { workspace = true }
