[package]
name = "tangram_cli"

description = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = false
repository = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }

[[bin]]
name = "tangram"
path = "src/main.rs"

[features]
foundationdb = ["dep:foundationdb", "tangram_server/foundationdb"]

[lints]
workspace = true

[dev-dependencies]
insta = { workspace = true }

[dependencies]
anstream = { workspace = true }
async-broadcast = { workspace = true }
byte-unit = { workspace = true }
bytes = { workspace = true }
clap = { workspace = true }
console-subscriber = { workspace = true }
copypasta = { workspace = true }
crossterm = { workspace = true }
deno_core_icudata = { workspace = true }
derive_more = { workspace = true }
foundationdb = { workspace = true, optional = true }
futures = { workspace = true }
indexmap = { workspace = true }
indoc = { workspace = true }
itertools = { workspace = true }
libc = { workspace = true }
miette = { workspace = true }
num = { workspace = true }
ratatui = { workspace = true }
serde = { workspace = true }
serde-untagged = { workspace = true }
serde_json = { workspace = true }
serde_with = { workspace = true }
tangram_client = { workspace = true }
tangram_either = { workspace = true }
tangram_futures = { workspace = true }
tangram_http = { workspace = true }
tangram_server = { workspace = true }
tangram_temp = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
tokio-stream = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tracing-tree = { workspace = true }
unicode-segmentation = { workspace = true }
unicode-width = { workspace = true }
url = { workspace = true }
urlencoding = { workspace = true }
v8 = { workspace = true }
webbrowser = { workspace = true }
