[package]
name = "tangram_cli"

description = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = false
repository = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }

[lints]
workspace = true

[[bin]]
name = "tg"
path = "src/main.rs"

[dependencies]
bytes = { workspace = true }
clap = { workspace = true }
console-subscriber = { workspace = true }
crossterm = { workspace = true }
dialoguer = { workspace = true }
either = { workspace = true }
futures = { workspace = true }
glob = { workspace = true }
indicatif = { workspace = true }
indoc = { workspace = true }
itertools = { workspace = true }
libc = { workspace = true }
num = { workspace = true }
ratatui = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_with = { workspace = true }
tangram_client = { workspace = true }
tangram_error = { workspace = true }
tangram_server = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
unicode-segmentation = { workspace = true }
unicode-width = { workspace = true }
url = { workspace = true }
v8 = { workspace = true }
webbrowser = { workspace = true }
