[package]
name = "tangram_cli"

description = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = false
repository = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }

[[bin]]
name = "tangram"
path = "src/main.rs"

[features]
boa = ["tangram_server/boa"]
default = ["js", "lmdb", "typescript", "v8"]
foundationdb = ["dep:foundationdb", "dep:tangram_fdb", "tangram_server/foundationdb"]
js = ["tangram_server/js"]
lmdb = ["tangram_server/lmdb"]
nats = ["tangram_server/nats"]
postgres = ["tangram_server/postgres"]
scylla = ["tangram_server/scylla"]
typescript = ["tangram_server/typescript", "v8"]
v8 = ["dep:v8", "tangram_server/v8"]

[lints]
workspace = true

[dependencies]
anstream = { workspace = true }
byte-unit = { workspace = true }
bytes = { workspace = true }
clap = { workspace = true }
clap_complete = { workspace = true }
clap_complete_nushell = { workspace = true }
comfy-table = { workspace = true }
console-subscriber = { workspace = true }
crossterm = { workspace = true }
data-encoding = { workspace = true }
deno_core_icudata = { workspace = true }
derive_more = { workspace = true }
foundationdb = { workspace = true, optional = true }
futures = { workspace = true }
indexmap = { workspace = true }
indoc = { workspace = true }
libc = { workspace = true }
miette = { workspace = true }
num = { workspace = true }
owo-colors = { workspace = true }
petgraph = { workspace = true }
radix_trie = { workspace = true }
ratatui = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_with = { workspace = true }
tangram_builtin = { workspace = true }
tangram_client = { workspace = true }
tangram_fdb = { workspace = true, optional = true }
tangram_futures = { workspace = true }
tangram_js = { workspace = true }
tangram_sandbox = { workspace = true }
tangram_server = { workspace = true }
tangram_session = { workspace = true }
tangram_uri = { workspace = true }
tangram_util = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
tokio-stream = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tracing-tree = { workspace = true }
unicode-segmentation = { workspace = true }
unicode-width = { workspace = true }
v8 = { workspace = true, optional = true }
webbrowser = { workspace = true }
xattr = { workspace = true }
