services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 5s
      retries: 10

  scylla:
    image: scylladb/scylla:latest
    command: --smp 1 --memory 512M --overprovisioned 1
    ports:
      - "9042:9042"
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'DESC KEYSPACES'"]
      interval: 1s
      timeout: 5s
      retries: 10

  nats:
    image: nats:latest
    command: --jetstream
    ports:
      - "4222:4222"
      - "8222:8222"
    healthcheck:
      test: ["CMD", "nats-server", "--help"]
      interval: 1s
      timeout: 5s
      retries: 10
