[package]
name = "tangram_language"

description = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = false
repository = { workspace = true }
version = { workspace = true }

[lints]
workspace = true

[build-dependencies]
v8 = { workspace = true }

[dev-dependencies]
bytes = { workspace = true }
futures = { workspace = true }
indoc = { workspace = true }
once_cell = { workspace = true }
proptest = { workspace = true }
tempfile = { workspace = true }

[dependencies]
async-recursion = { workspace = true }
async-trait = { workspace = true }
base64 = { workspace = true }
bytes = { workspace = true }
derive_more = { workspace = true }
fnv = { workspace = true }
futures = { workspace = true }
hex = { workspace = true }
im = { workspace = true }
include_dir = { workspace = true }
itertools = { workspace = true }
lsp-types = { workspace = true }
num = { workspace = true }
semver = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_v8 = { workspace = true }
serde_yaml = { workspace = true }
sourcemap = { workspace = true }
swc_core = { workspace = true }
tangram_client = { workspace = true }
tangram_error = { workspace = true }
tokio = { workspace = true }
toml = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }
v8 = { workspace = true }
