[package]
name = "tangram_messenger"

description = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = false
repository = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }

[lints]
workspace = true

[features]
nats = ["dep:async-nats"]

[dependencies]
async-broadcast = { workspace = true }
async-nats = { workspace = true, optional = true }
bytes = { workspace = true }
dashmap = { workspace = true }
derive_more = { workspace = true }
futures = { workspace = true }
num = { workspace = true }
tangram_either = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }